name: build-and-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: "6.0.x"
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build TypedSignalR.Client.TypeScript.csproj
        run: dotnet build ./src/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript.csproj --no-restore

      - name: Build TypedSignalR.Client.TypeScript.Analyzer.csproj
        run: dotnet build ./src/TypedSignalR.Client.TypeScript.Analyzer/TypedSignalR.Client.TypeScript.Analyzer.csproj --no-restore

      - name: Build TypedSignalR.Client.TypeScript.Attributes.csproj
        run: dotnet build ./src/TypedSignalR.Client.TypeScript.Attributes/TypedSignalR.Client.TypeScript.Attributes.csproj --no-restore

      - name: Build TypedSignalR.Client.TypeScript.Generator.csproj
        run: dotnet build ./src/TypedSignalR.Client.TypeScript.Generator/TypedSignalR.Client.TypeScript.Generator.csproj --no-restore

      - name: Launch test server
        run: dotnet run --project ./tests/TypedSignalR.Client.TypeScript.Tests.Server/TypedSignalR.Client.TypeScript.Tests.Server.csproj --no-restore &

      - name: Generate TypeScript code for test
        run: dotnet run --project ./src/TypedSignalR.Client.TypeScript.Generator/TypedSignalR.Client.TypeScript.Generator.csproj --no-build -- --project ./tests/TypedSignalR.Client.TypeScript.Tests.Shared/TypedSignalR.Client.TypeScript.Tests.Shared.csproj --output ./tests/TypeScriptTests/src/generated/

      - name: Install yarn
        run: npm install -g yarn

      - name: Yarn install
        run: yarn --cwd ./tests/TypeScriptTests/ install

      - name: Yarn Test
        run: yarn --cwd ./tests/TypeScriptTests/ test
